### +Get persons
GET http://localhost:3001/api/persons

### -Get unknown endpoint
GET http://localhost:3001/unknown_resource

### +Get existing person
GET http://localhost:3001/api/persons/6352ee35ed54b8105f165669

### -Get non-existing person
GET http://localhost:3001/api/persons/6352c77ff6d76fab6a3c6010

### -Get malformed id
GET http://localhost:3001/api/persons/notanid

### +Get frontend
GET http://localhost:3001/