### +Get existing person
GET http://localhost:3001/api/persons/6352ee35ed54b8105f165669

### +Post unique person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Unique person",
  "number": "01234-5678"
}

### -+Delete person
DELETE http://localhost:3001/api/persons/<valid_id>

### +Update existing person number
PUT http://localhost:3001/api/persons/6352ee35ed54b8105f165669
Content-Type: application/json

{
  "name": "DO NOT DELETE ",
  "number": "01234-5678"
} 
