###
GET  http://localhost:3001/api/notes

###
POST  http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": true
}

### Create user
POST  http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "user",
    "name": "Tester",
    "password": "password"
}

### Login user
POST  http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "user",
    "password": "password"
}

### Get users
GET  http://localhost:3001/api/users